addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.2.0")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.4.0")
addSbtPlugin("org.scalameta"      % "sbt-mdoc"                      % "2.3.2")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"                % "1.5.10")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"                  % "0.10.0")
